import React from 'react';
import * as All from '../../lib/components';

const Adobe = ({ darkMode }) => {
  return (
    <fieldset>
      <legend>Adobe</legend>
      <div className='icon-group'>
        <All.AcrobatDC
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease'
        />
        <All.AcrobatOnline
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease'
        />
        <All.AfterEffects
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Animate
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Audition
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Behance
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Bridge
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.CharacterAnimator
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.CreativeCloud
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.CreativeCloudAlt
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Dimension
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.DocumentCloud
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Dreamweaver
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.ExperienceCloud
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Fonts
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Fuse
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.Illustrator
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.InCopy
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
        <All.InDesign
          width='3rem'
          height='3rem'
          color={false}
          theme={darkMode}
          primaryDark='#343434'
          primaryWhite='#f4f4f4'
          hover={'colorize'}
          transition='ease-in'
        />
      </div>
    </fieldset>
  );
};

export default Adobe;
